### ISSUE TITLE
Get rid of `--add-opens` workaround, and turn it into a modifier shipped with running-ng

### ISSUE THREAD

**Issue by caizixian** [anupli/running-ng#130]
It's currently not sufficient.

```
  h2o21:
    type: JVMArg
    val: "-Dsys.ai.h2o.debug.allowJavaVersions=21 --add-opens java.base/java.lang=ALL-UNNAMED"
    includes:
      dacapochopin-rc5:
        - h2o
  cassandra21:
    type: JVMArg
    val: "-Djava.security.manager=allow --add-exports java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED"
    includes:
      dacapochopin-rc5:
        - cassandra
  trades21:
    type: JVMArg
    val: "--add-opens java.base/java.util=ALL-UNNAMED"
    includes:
      dacapochopin-rc5:
        - tradebeans
        - tradesoap
```
