### ISSUE TITLE
Support more flexible heap size modifiers

### ISSUE THREAD

**Issue by caizixian** [anupli/running-ng#140]
Proposed by @wks 

```yaml
modifiers:
  heap2x:
    type: HeapSize
    multiplier: 2
  heap64m:
    type: HeapSize
    size: "64M"
  heapdyn:
    type: HeapSize
    min: "1M"
    max: "128G"
configs:
  - "build1|mmtk_gc-Immix|heap2x"
  - "build1|mmtk_gc-Immix|heap64m"
  - "build1|mmtk_gc-Immix|heapdyn"
```
